### PR TITLE
Fix driver.Sql with Stream.Operator finder.

### LINKED ISSUE #338: database/sql ORDER BY error
Loving genji so far - thanks!

### What version of Genji are you using?
<pre>
v0.9.1-0.20210105060628-b0134220aac3
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

When using the database/sql driver, adding an `ORDER BY x` clause (with or without a direction) to a filtered `SELECT` query returns an error.  The same `SELECT` with `ORDER BY` clause using the Genji API works as expected.

Minimal example:
https://play.golang.org/p/F5bfkULNCWd

### What did you expect to see?

An dump of a and b values, ordered by a.

### What did you see instead?

`ERROR 1: sql: expected 0 destination arguments in Scan, not 2` unless the `ORDER BY a` is removed.

### What Go version and environment are you using?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/Code/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/Code/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/Code/gocode/src/github.com/hynd/genjitest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3r/_jv56wbj2xb6gwh9pkv9y62cg1_7cm/T/go-build810324326=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### PR DESCRIPTION
**Pull request by tzzed**
This fixes #338.

### CODE REVIEW

File: sql/driver/driver.go [hunk 1]
```diff
@@ -311,7 +316,7 @@ func (s stmt) Close() error {
 	return nil
 }
 
-var errStop = errors.New("stop")
+var ErrStop = errors.New("stop")
```
Comment (asdine) [inline sql/driver/driver.go:319]: Is there a reason for unexporting this?

**Review by asdine — APPROVED** [review]
Thanks @tzzed !
