### PR TITLE
Explicit message error for ErrTableNotFound

### LINKED ISSUE #238: Explicit message error for table that doesn't exist
Currently when we request a  table that doesn't exist we got the error `table not found`.
This can be complicated to debug especially at the API's level.
I think we should be more explicit
``` SQL
genji> SELECT * FROM foo; 
table not found
genji>
```

```SQL
sqlite> SELECT * FROM foo;
Error: no such table: foo
sqlite>
```

### PR DESCRIPTION
**Pull request by carlosfrodrigues**
Hello, 
I changed my pull request, now it's passing in all the tests and building in travis CI.
Closes #238

### CODE REVIEW

File: database/config_test.go [hunk 1]
```diff
@@ -64,15 +65,15 @@ func TestTableInfoStore(t *testing.T) {
 
 		// Getting a non-existing TableInfo should not work.
 		_, err = tx.tableInfoStore.Get(tx, "unknown")
-		require.Equal(t, ErrTableNotFound, err)
+		require.Equal(t, fmt.Errorf("%w: %q", ErrTableNotFound, "unknown"), err)
```
Comment (tie) [inline database/config_test.go:68]:
```suggestion
		require.ErrorIs(t, err, ErrTableNotFound)
```

File: database/config_test.go [hunk 2]
```diff
@@ -64,15 +65,15 @@ func TestTableInfoStore(t *testing.T) {
...
 
 		// Deleting an existing TableInfo should work.
 		err = tx.tableInfoStore.Delete(tx, "foo1")
 		require.NoError(t, err)
 
 		// Deleting a non-existing TableInfo should not work.
 		err = tx.tableInfoStore.Delete(tx, "foo1")
-		require.Equal(t, ErrTableNotFound, err)
+		require.Equal(t, fmt.Errorf("%w: %q", ErrTableNotFound, "foo1"), err)
```
Comment (tie) [inline database/config_test.go:76]:
```suggestion
		require.ErrorIs(t, err, ErrTableNotFound)
```

Comment (carlosfrodrigues) [reply database/config_test.go:76]: Oh thanks, I will change that

File: database/errors.go [hunk 3]
```diff
@@ -6,7 +6,8 @@ import (
 
 var (
 	// ErrTableNotFound is returned when the targeted table doesn't exist.
-	ErrTableNotFound = errors.New("table not found")
+	// The table name is added to the error.
+	ErrTableNotFound = errors.New("Error: no such table:")
```
Comment (tie) [inline database/errors.go:10]: There is no need to change this. See [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#error-strings).

```suggestion
	ErrTableNotFound = errors.New("table not found")
```

**Comment by carlosfrodrigues** [comment]
Applied all the suggestions

File: database/config_test.go (hunk 2 above)
Comment (carlosfrodrigues) [reply database/config_test.go]: Hi,
I commited this suggestion but there is no require.ErrorIs and now the build is failing.

Is there something I didn't understand?
Thank you

**Comment by tie** [comment]
@carlosfrodrigues sorry about that! It appears that `require.ErrorIs` was added in https://github.com/stretchr/testify/commit/95a9d909e98735cd8211dfc5cbbb6b8b0b665915 which is not released yet.

We should change `require.ErrorIs` to
```
if !errors.Is(err, database.ErrTableNotFound) {
	require.Equal(err, database.ErrTableNotFound)
}
```

I’ll create suggestions for that.

File: database/config_test.go [hunk 4]
```diff
@@ -64,15 +65,15 @@ func TestTableInfoStore(t *testing.T) {
 
 		// Getting a non-existing TableInfo should not work.
 		_, err = tx.tableInfoStore.Get(tx, "unknown")
-		require.Equal(t, ErrTableNotFound, err)
+		require.ErrorIs(t, err, ErrTableNotFound)
```
Comment (tie) [inline database/config_test.go:68]:
```suggestion
	if !errors.Is(err, ErrTableNotFound) {
		require.Equal(t, err, ErrTableNotFound)
	}
```

File: database/config_test.go [hunk 5]
```diff
@@ -1,6 +1,7 @@
 package database
 
 import (
+	"fmt"
```
Comment (tie) [inline database/config_test.go:4]:
```suggestion
	"errors"
```

File: database/config_test.go [hunk 6]
```diff
@@ -64,15 +65,15 @@ func TestTableInfoStore(t *testing.T) {
...
+		require.ErrorIs(t, err, ErrTableNotFound)
 
 		// Deleting an existing TableInfo should work.
 		err = tx.tableInfoStore.Delete(tx, "foo1")
 		require.NoError(t, err)
 
 		// Deleting a non-existing TableInfo should not work.
 		err = tx.tableInfoStore.Delete(tx, "foo1")
-		require.Equal(t, ErrTableNotFound, err)
+		require.ErrorIs(t, err, ErrTableNotFound)
```
Comment (tie) [inline database/config_test.go:76]:
```suggestion
		if !errors.Is(err, ErrTableNotFound) {
			require.Equal(t, err, ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 7]
```diff
@@ -79,7 +79,7 @@ func TestTxTable(t *testing.T) {
 
 		// Getting a table that doesn't exist should fail.
 		_, err = tx.GetTable("unknown")
-		require.EqualError(t, err, database.ErrTableNotFound.Error())
+		require.EqualError(t, err, fmt.Errorf("%w: %q", database.ErrTableNotFound, "unknown").Error())
```
Comment (tie) [inline database/transaction_test.go:82]:
```suggestion
		if !errors.Is(err, database.ErrTableNotFound) {
			require.Equal(t, err, database.ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 8]
```diff
@@ -2,7 +2,7 @@ package database_test
 
 import (
 	"testing"
-
+	"fmt"
```
Comment (tie) [inline database/transaction_test.go:5]: Not needed now. Import `errors` package above `testing`.

File: database/transaction_test.go [hunk 9]
```diff
@@ -94,11 +94,11 @@ func TestTxTable(t *testing.T) {
 
 		// Getting a table that has been dropped should fail.
 		_, err = tx.GetTable("test")
-		require.EqualError(t, err, database.ErrTableNotFound.Error())
+		require.EqualError(t, err, fmt.Errorf("%w: %q", database.ErrTableNotFound, "test").Error())
```
Comment (tie) [inline database/transaction_test.go:97]:
```suggestion
		if !errors.Is(err, database.ErrTableNotFound) {
			require.Equal(t, err, database.ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 10]
```diff
@@ -94,11 +94,11 @@ func TestTxTable(t *testing.T) {
...
 
 		// Dropping a table that doesn't exist should fail.
 		err = tx.DropTable("test")
-		require.EqualError(t, err, database.ErrTableNotFound.Error())
+		require.EqualError(t, err, fmt.Errorf("%w: %q", database.ErrTableNotFound, "test").Error())
```
Comment (tie) [inline database/transaction_test.go:101]:
```suggestion
		if !errors.Is(err, database.ErrTableNotFound) {
			require.Equal(t, err, database.ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 11]
```diff
@@ -124,7 +124,7 @@ func TestTxTable(t *testing.T) {
 
 		// Getting the old table should return an error.
 		_, err = tx.GetTable("foo")
-		require.EqualError(t, database.ErrTableNotFound, err.Error())
+		require.EqualError(t, err, fmt.Errorf("%w: %q", database.ErrTableNotFound, "foo").Error())
```
Comment (tie) [inline database/transaction_test.go:127]:
```suggestion
		if !errors.Is(err, database.ErrTableNotFound) {
			require.Equal(t, err, database.ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 12]
```diff
@@ -144,7 +144,7 @@ func TestTxTable(t *testing.T) {
 
 		// Renaming a non existing table should return an error
 		err = tx.RenameTable("foo", "")
-		require.EqualError(t, database.ErrTableNotFound, err.Error())
+		require.EqualError(t, err, fmt.Errorf("%w: %q", database.ErrTableNotFound, "foo").Error())
```
Comment (tie) [inline database/transaction_test.go:147]:
```suggestion
		if !errors.Is(err, database.ErrTableNotFound) {
			require.Equal(t, err, database.ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 13]
```diff
@@ -190,7 +190,7 @@ func TestTxCreateIndex(t *testing.T) {
 		err := tx.CreateIndex(database.IndexConfig{
 			IndexName: "idxFoo", TableName: "test", Path: parsePath(t, "foo"),
 		})
-		require.Equal(t, database.ErrTableNotFound, err)
+		require.Equal(t, fmt.Errorf("%w: %q", database.ErrTableNotFound, "test"), err)
```
Comment (tie) [inline database/transaction_test.go:193]:
```suggestion
		if !errors.Is(err, database.ErrTableNotFound) {
			require.Equal(t, err, database.ErrTableNotFound)
		}
```

File: sql/query/alter_test.go [hunk 14]
```diff
@@ -33,7 +34,7 @@ func TestAlterTable(t *testing.T) {
 
 	// Selecting from the old name should fail.
 	err = db.Exec(ctx, "SELECT * FROM foo")
-	require.EqualError(t, err, database.ErrTableNotFound.Error())
+	require.EqualError(t, err, fmt.Errorf("%w: %q", database.ErrTableNotFound, "foo").Error())
```
Comment (tie) [inline sql/query/alter_test.go:37]:
```suggestion
	if !errors.Is(err, database.ErrTableNotFound) {
		require.Equal(t, err, database.ErrTableNotFound)
	}
```

File: sql/query/alter_test.go [hunk 15]
```diff
@@ -2,6 +2,7 @@ package query_test
 
 import (
 	"context"
+	"fmt"
```
Comment (tie) [inline sql/query/alter_test.go:5]:
```suggestion
	"errors"
```

File: sql/query/reindex.go [hunk 16]
```diff
@@ -30,7 +31,7 @@ func (stmt ReIndexStmt) Run(ctx context.Context, tx *database.Transaction, args
 	if err == nil {
 		return res, t.ReIndex()
 	}
-	if err != database.ErrTableNotFound {
+	if !(errors.Is(err, database.ErrTableNotFound)) {
```
Comment (tie) [inline sql/query/reindex.go:34]:
```suggestion
	if !errors.Is(err, database.ErrTableNotFound) {
```

**Review by tie — CHANGES_REQUESTED** [review]
Thanks for these changes! Again, sorry for suggestion using the unreleased `require.ErrorIs`.

There are some minor changes to be made, but overall this PR looks good to me!

File: database/config_test.go [hunk 17]
```diff
@@ -64,15 +65,19 @@ func TestTableInfoStore(t *testing.T) {
 
 		// Getting a non-existing TableInfo should not work.
 		_, err = tx.tableInfoStore.Get(tx, "unknown")
-		require.Equal(t, ErrTableNotFound, err)
+	if !errors.Is(err, ErrTableNotFound) {
+		require.Equal(t, err, ErrTableNotFound)
+	}
```
Comment (tie) [inline database/config_test.go:70]:
```suggestion
		if !errors.Is(err, ErrTableNotFound) {
			require.Equal(t, err, ErrTableNotFound)
		}
```

File: database/transaction_test.go [hunk 18]
```diff
@@ -2,7 +2,7 @@ package database_test
 
 import (
 	"testing"
```
Comment (tie) [inline database/transaction_test.go:4]:
```suggestion
	"errors"
	"testing"
```

File: cmd/genji/shell/command.go [hunk 19]
```diff
@@ -313,21 +313,21 @@ func runDumpCmd(db *genji.DB, tables []string, w io.Writer) error {
...
+			// If table doesn’t exist we skip it.
+			if errors.Is(err, database.ErrTableNotFound) {
+				continue
 			}
-
-		case fmt.Errorf("%w: %q", database.ErrTableNotFound, table): // If table doesn't exist we skip it.
-			continue
-		default:
-			_, err = fmt.Fprintln(w, "COMMIT;")
+			_, err = fmt.Println(w, "COMMIT;")
```
Comment (tie) [inline cmd/genji/shell/command.go:321]: Oops, should have been `Fprintln` here since we are writing to an `io.Writer`.

```suggestion
			_, err = fmt.Fprintln(w, "COMMIT;")
```

File: database/transaction_test.go [hunk 20]
```diff
@@ -1,8 +1,7 @@
 package database_test
 
 import (
-	"testing"
-
+	"errors"
```
Comment (tie) [inline database/transaction_test.go:4]:
```suggestion
	"errors"
	"testing"
```

File: database/transaction_test.go [hunk 21]
```diff
@@ -1,8 +1,9 @@
 package database_test
 
 import (
+	"errors"
```
Comment (tie) [inline database/transaction_test.go:4]: Ouch, we already have `errors` imported here.

```suggestion
```

File: cmd/genji/shell/command.go [hunk 22]
```diff
@@ -313,21 +313,21 @@ func runDumpCmd(db *genji.DB, tables []string, w io.Writer) error {
...
-		switch err {
-		case nil:
-			// Blank separation between tables.
-			if i > 0 {
-				if _, err := fmt.Fprintln(w, ""); err != nil {
-					return err
-				}
+		if err != nil {
+			// If table doesn’t exist we skip it.
+			if errors.Is(err, database.ErrTableNotFound) {
```
Comment (tie) [inline cmd/genji/shell/command.go:318]: We need to import `errors` package in this file too.

**Review by tie — APPROVED** [review]

**Comment by tie** [comment]
Closes #238

**Review by asdine — APPROVED** [review]
That looks great! Thanks @carlosfrodrigues and @tie !
