### PR TITLE
Fixes .Indexes and .tables commands error handler and tests

### LINKED ISSUE #233: Regression in .indexes command
Running `.indexes t` should print `table not found` if table `t` does not exist.

```
--- FAIL: TestRunTablesCmd (0.00s)
    --- FAIL: TestRunTablesCmd/Table_with_options (0.00s)
        command_test.go:38: 
            	Error Trace:	command_test.go:38
            	Error:      	An error is expected but got nil.
            	Test:       	TestRunTablesCmd/Table_with_options
            	Messages:   	%!(EXTRA bool=true)
```

See also: #232

### PR DESCRIPTION
**Pull request by tzzed**
Fixes #233 

`command_test.go` had some errors.
`.Indexes` returns `table not found`

### CODE REVIEW

File: cmd/genji/shell/command.go [hunk 1]
```diff
@@ -60,6 +60,11 @@ func displayTableIndex(db *genji.DB, tableName string) error {
 	}
 	defer res.Close()
 
+	_, err = res.Tx.GetTable(tableName)
```
Comment (tie) [inline cmd/genji/shell/command.go:63]: I think we can select from `__genji_tables`.

https://github.com/genjidb/genji/blob/6aa01a11de96f2da7336b25d38c42d6509e9db69/cmd/genji/shell/shell.go#L435

Comment (tzzed) [reply cmd/genji/shell/command.go:63]: You're it's a better way.

Comment (tzzed) [reply cmd/genji/shell/command.go:63]: You're right it's a better way.

File: cmd/genji/shell/command.go [hunk 2]
```diff
@@ -53,6 +53,15 @@ func runTablesCmd(db *genji.DB, cmd []string) error {
...
+	switch err {
+	case database.ErrDocumentNotFound:
+		return database.ErrTableNotFound
+	case nil:
+		// nop
+	default:
+		return err
+	}
 
 	res, err := db.Query(ctx, "SELECT * FROM __genji_indexes WHERE table_name = ?", tableName)
```
Comment (tie) [inline cmd/genji/shell/command.go:66]: Both queries should be in the same transaction (using `db.View`).

Comment (tzzed) [reply cmd/genji/shell/command.go]: thank you @tie

**Review by tie — APPROVED** [review]
LGTM 👍

**Review by yaziine — APPROVED** [review]
Thanks for handling this @tzzed, I left just one small comment.

**Review by asdine — APPROVED** [review]
Thanks!
